### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Shivansh-yadav13** [casbin/json-adapter#3]
**Getting this error for every enforcer method**
please fix me if I'm doing something wrong.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x42722d]

goroutine 1 [running]:
github.com/casbin/casbin/v2.(*Enforcer).LoadPolicy(0x0)
        C:/Users/Admin/go/pkg/mod/github.com/casbin/casbin/v2@v2.41.1/enforcer.go:284 +0x4d
main.main()
        T:/dev/go_json_casbin_tesdt/main.go:16 +0xe7
exit status 2  
```

```go
package main

import (
	"github.com/casbin/casbin/v2"
	"github.com/casbin/json-adapter/v2"
)

func main() {
	b := []byte{}
	a := jsonadapter.NewAdapter(&b)
	e, _ := casbin.NewEnforcer("examples/rbac_model.conf", a)
	e.LoadPolicy()
}
```

**Comment by Shivansh-yadav13** [comment]
sorry for raising the issue
